# Generated by Django 5.2.1 on 2025-05-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_career_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='resume_pdf_url',
        ),
        migrations.AddField(
            model_name='applicant',
            name='ai_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='current_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='parsed_education',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='parsed_resume_raw',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='parsed_skills',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='parsed_work_experience',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='resume_pdf',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='years_experience',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
