# Generated by Django 5.2.1 on 2025-05-26 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_career_app', '0002_remove_applicant_resume_pdf_url_applicant_ai_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='ai_score',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='job_posting',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='parsed_education',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='parsed_resume_raw',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='parsed_skills',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='parsed_work_experience',
        ),
        migrations.AddField(
            model_name='applicant',
            name='graduate_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='latest_degree',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='major',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_score', models.FloatField(blank=True, null=True)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_career_app.jobposting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='tags',
            field=models.ManyToManyField(blank=True, to='django_career_app.tag'),
        ),
    ]
