# Generated by Django 5.2.1 on 2025-05-28 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_career_app', '0005_applicant_resume_markdown_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='description',
            field=models.TextField(help_text='A general description of the company. Use Markdown for formatting.'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='description',
            field=models.TextField(help_text='Detailed description of the job, responsibilities, and qualifications. Use Markdown for formatting.'),
        ),
    ]
