# Generated by Django 5.2.1 on 2025-06-03 02:49

import django_career_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_career_app', '0006_alter_companyprofile_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='resume_pdf',
            field=models.FileField(blank=True, help_text="Stores the applicant's resume file (PDF format preferred).", null=True, storage=django_career_app.models.select_storage, upload_to='resumes/'),
        ),
    ]
