# Generated by Django 5.2.1 on 2025-06-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_career_app', '0007_remove_applicant_email_remove_applicant_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='location',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='name',
            field=models.CharField(default='Company', help_text='The name of the company.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='url',
            field=models.URLField(blank=True, help_text="URL to the company's website.", null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='city',
            field=models.CharField(default='Chicago', help_text='City of the job location.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobposting',
            name='country',
            field=models.CharField(blank=True, help_text='Country of the job location.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='state_or_province',
            field=models.CharField(blank=True, help_text='State or province of the job location.', max_length=255, null=True),
        ),
    ]
