# Generated by Django 5.2.1 on 2025-06-03 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_career_app', '0008_remove_jobposting_location_companyprofile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='company_profile',
            field=models.ForeignKey(blank=True, help_text='The company profile associated with this job posting.', null=True, on_delete=django.db.models.deletion.CASCADE, to='django_career_app.companyprofile'),
        ),
    ]
